### ISSUE TITLE
Framework for UI testing

### ISSUE THREAD

**Issue by psrna** [redhat-developer/vscode-quarkus#102]
This could be worth exploring for UI testing: https://github.com/redhat-developer/vscode-extension-tester

**Comment by xorye** [comment]
Thank you for bringing this to our attention. I will close this issue because we started adding UI tests with: https://github.com/redhat-developer/vscode-quarkus/pull/172.

We will continue to add more UI tests: https://github.com/redhat-developer/vscode-quarkus/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Adebt+Tests+for
