### ISSUE TITLE
double formatters for java

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-quarkus#207]
latest version of quarkus tools asks me to choose wether want to use quarkus or vscode-java for java formatting.

That shouldn't happen should it ? 

I tried make a screenshot but it disappeared when trying to grab it.

**Comment by angelozerr** [comment]
Indeed there is a problem with java, the problem comes fromMicriProfile LS which maneges java and application.properties both. The server returns the format capability because application.properties can be formatted, but returning this format capability provides trouble with java althouth MicroProfile LS can just formatting application.properties files.

There are 2 solutions to fix this java format problem:

 * Separate java and application.properties support in 2 language server.
 * Improve JDT LS to override features like hover, codelens, diagnostics, etc

We need to discuss about that with @fbricon 

I close this issue since this issue is similar to https://github.com/redhat-developer/vscode-quarkus/issues/166
