### ISSUE TITLE
Add support for MicroProfile Reactive Messaging

### ISSUE THREAD

**Issue by tivrfoa** [redhat-developer/vscode-quarkus#218]
Hi,

The plugin doesn't recognize "mp.messaging" properties in application.properties.
These are used for example in the Kafka guide:
https://quarkus.io/guides/kafka
```
# Configure the Kafka sink (we write to it)
mp.messaging.outgoing.generated-price.connector=smallrye-kafka
mp.messaging.outgoing.generated-price.topic=prices
```
...
![Screenshot from 2020-02-25 12-29-58](https://user-images.githubusercontent.com/30683/75262759-bc754100-57cb-11ea-84e2-68ca3190fa4d.png)

**Comment by fbricon** [comment]
@tivrfoa you can get rid of the warnings by ignoring `mp.messaging.*` from validation. See available code actions
<img width="669" alt="Screen Shot 2020-02-25 at 5 09 08 PM" src="https://user-images.githubusercontent.com/148698/75265717-95ca0100-57f1-11ea-929c-f3e3b223eab1.png">

**Comment by angelozerr** [comment]
@cescoffier @tivrfoa I suppose those mp properties are managed by https://github.com/smallrye/smallrye-reactive-messaging 

Have you an idea where there are managed? I would like to avoid hard coding those properties if it's possible.

**Comment by tivrfoa** [comment]
> @cescoffier @tivrfoa I suppose those mp properties are managed by https://github.com/smallrye/smallrye-reactive-messaging
> 
> Have you an idea where there are managed? I would like to avoid hard coding those properties if it's possible.

I don't know. I found some info on the link below (page 29), but I don't think it is enough to help you.
https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.pdf

[quote]
> Configuration

Reactive  Messaging  connectors  are  configured  using  MicroProfile  Config. 
The  implementationprocesses the global configuration and determines:
  - which channels are defined
  - which connectors are used (using the connector) attribute
  - the configuration for each channel
  
The builder methods defined in the IncomingConnectorFactory and OutgoingConnectorFactory receivea org.eclipse.microprofile.config.Config as parameter.
The Config object contains key-value pairsto  configure  the  connector. 
The  configuration  is  specific  to  the  connector.  For  example,  a  Kafkaconnector expects a bootstrap.servers entry as well as a topic entry.

The  Reactive  Messaging  implementation  reads  the  global  application  configuration  and  mustsupport the following format:
  - mp.messaging.incoming.[channel-name].[attribute]=[value]
  - mp.messaging.outgoing.[channel-name].[attribute]=[value]
  - mp.messaging.connector.[connector-name].[attribute]=[value]
[/quote]

**Comment by tivrfoa** [comment]
> I don't know. I found some info on the link below (page 29), but I don't think it is enough to help you.

> https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.pdf`


I think this link is more updated:
https://github.com/eclipse/microprofile-reactive-messaging/blob/master/spec/src/main/asciidoc/architecture.asciidoc

**Comment by angelozerr** [comment]
Thanks @tivrfoa for your information. After studying how properties are built, I'm afraid it's not possible to do it, because a lot of things are hard coded.

Takes a sample with:

```
# Configure the Kafka sink (we write to it)
mp.messaging.outgoing.generated-price.connector=smallrye-kafka
mp.messaging.outgoing.generated-price.topic=prices
```

 * The `mp.messaging.outgoing.generated-price.connector` can be easily generated by scanning `Outgoing` annotation from classpath, get the value of Outgoing annotation (in this sample it's generated-price) and add `connector`. 

 * for the `smallrye-kafka` value, the idea is to scan @Connector annotation. See https://github.com/smallrye/smallrye-reactive-messaging/blob/b91e05a0df00bc0cfd302184d4c5663eac2c342b/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java#L27 (the difficulty is that connector name is declared in a constant (`@Connector(VertxEventBusConnector.CONNECTOR_NAME)`) so I don't know if it's an easy task in JDT to retrieve the value. It should be more simplifier if we have (`@Connector("smallrye-kafka")`)

 * `mp.messaging.outgoing.generated-price.topic`, I'm afraid it's impossible to generate this property, because it'shard coded, in https://github.com/smallrye/smallrye-reactive-messaging/blob/b91e05a0df00bc0cfd302184d4c5663eac2c342b/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java#L67 it initialize the topic of KafkaSource  https://github.com/smallrye/smallrye-reactive-messaging/blob/b91e05a0df00bc0cfd302184d4c5663eac2c342b/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/impl/KafkaSource.java#L114

**Comment by angelozerr** [comment]
I'm working on this issue, I close it for https://github.com/eclipse/lsp4mp/issues/26
