### ISSUE TITLE
Create/Update Quarkus snippets

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer/vscode-quarkus#227]
Create new snippets for the new container-image extension: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/container-image.adoc

So the configuration to push a container image to a remote registry is automatically set.

Update the snippet for defining a data source to the latest changes using `db-kind` instead of a driver.  https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/datasource.adoc#jdbc-datasource

**Comment by angelozerr** [comment]
@lordofthejars thanks for this issue. I would like to manage snippet on server side (and not on vscode client side) because :

 * all client (vscode, Eclipse IDE) could benefit with that
 * we will able to provide those snippet only when project will have the proper dependency.

See https://github.com/redhat-developer/vscode-quarkus/issues/119

I have already managed that in an another project (XML maven extension), the idea is that you describe your snippet in json file with the same format than vscode, but you host those files in the server side with a condition (in the Quarkus context, the condition is the extension name). If you have time to write those snippets in a PR (I mean just writing snippets, not the package.json declaration, it should be very cool). Thanks

**Comment by angelozerr** [comment]
@lordofthejars is there any chance that you write vscode snippets and after that we will able to integrate on MicroProfile Language Server ?

**Comment by lordofthejars** [comment]
Ok, I'll do it ASAP, no worries.

**Comment by angelozerr** [comment]
> Ok, I'll do it ASAP, no worries.

Thanks!

**Comment by lordofthejars** [comment]
For container images:

```json
"Add Container Image properties": {
		"prefix": "cip",
		"body": [
			"quarkus.container-image.group=$1",
			"quarkus.container-image.registry=${2:quay.io}",
			"quarkus.kubernetes.expose=${3|true,false|}",
			"#quarkus.container-image.username=$4",
			"#quarkus.container-image.password=$5"
		]
	}
```

DataSource:

```json
"Add Panache properties": {
		"prefix": "qpm",
		"body": [
			"quarkus.datasource.url=${1:jdbc:mariadb://localhost:3306/mydb}",
			"quarkus.datasource.db-kind=${2|h2,derby,mariadb,mssql,mysql,postgresql|}",
			"quarkus.datasource.username=${3:developer}",
			"quarkus.datasource.password=${4:developer}",
			"quarkus.hibernate-orm.database.generation=${4:update}"
		],
		"description": "Configure Quarkus Panache"
	},
```

**Comment by fbricon** [comment]
We already have the datasource snippet (see #90 and #92). Triggered with `qds`

**Comment by lordofthejars** [comment]
@fbricon See that a new property has been added, this was what I was showing here so driver is not required anymore.

**Comment by angelozerr** [comment]
@lordofthejars could you review https://github.com/redhat-developer/quarkus-ls/pull/310/files please

**Comment by fbricon** [comment]
So only the datasource snippet was updated, as the container story is not ready yet. See https://github.com/redhat-developer/quarkus-ls/pull/310#discussion_r417490326
