### ISSUE TITLE
Ignore kafka-streams namespace by default

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#314]
According to https://github.com/quarkusio/quarkusio.github.io/blame/develop/_guides/kafka-streams.adoc#L469:

> All the properties within the `kafka-streams` namespace are passed through as-is to the Kafka Streams engine.

So the kafka-streams.* namespace should be ignored by default.

Check https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-streams-quickstart/aggregator/src/main/resources/application.properties

When manually excluding "kafka-streams.*", %test.kafka-streams.state.dir still shows up as unknown property
<img width="1373" alt="Screen Shot 2020-10-22 at 7 02 54 PM" src="https://user-images.githubusercontent.com/148698/96905797-3b289800-1499-11eb-8c60-8c4bc39a5020.png">

**Comment by rgrunber** [comment]
Regarding the profile properties not being excluded from diagnostics : This is due to [MicroProfileValidator](https://github.com/eclipse/lsp4mp/blob/2ae65e635c258ca2eb3b4b36cd67a9f531f7d975/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/services/MicroProfileValidator.java#L105) not excluding the profile segment of the property when matching against the exclude list pattern.

I'll create change against lsp4mp to deal with this.
