### ISSUE TITLE
Wrong/Missing Log Levels in application.properties

### ISSUE THREAD

**Issue by Faboli7** [redhat-developer/vscode-quarkus#315]
Hi,

Autocomplete for Log Levels has issues.

For all the log level properties except quarkus.log.category.key.level, the proposed levels are the ones from java.util.logging, which means that setting FATAL, ERROR, WARN, DEBUG or TRACE is detected as an error.

For quarkus.log.category.key.level, two more levels are available: ERROR and DEBUG, but the other ones are missing too.

According to [this issue](https://github.com/quarkusio/quarkus/issues/5789) (see quote below), the levels that users are expected to use are the ones from JBoss Log Manager. The JUL ones are there only for compatibility reasons.

> As far as the Quarkus documentation goes: it was, in my view, an error (due to overzeal) to document anything other than the Apache levels. Those are the levels we expect users to use and configure. The JUL levels are worthy, perhaps, of a footnote, for cases where older Sun frameworks are used (for example) and the user needs to know how to map those levels on to the Apache ones for the purposes of configuring log categories. But this is one case where what is in the JDK is not really the standard that is used by the majority of developers. Documenting them as if they were serves only to add confusion.

The JBoss Log Manager levels should be added to the autocomplete (or used instead of JUL ones if not possible to combine them) to avoid having the properties marked as errors in VS code.

Thanks in advance.

**Comment by angelozerr** [comment]
Today LEVEL are hard coded on MicroProfile LS side https://github.com/eclipse/lsp4mp/blob/master/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/resources/org/eclipse/lsp4mp/model/values/quarkus-values-rules.json but it was a bad idea. (This issue is a sample of the limitation).

I had created the issue https://github.com/eclipse/lsp4mp/issues/39 but I need more investigation. The basic idea is that MP JDT should return the list of logger level.

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lsp4mp/pull/105 and https://github.com/redhat-developer/quarkus-ls/pull/370

@Faboli7 see the following demos:

![LevelDemo](https://user-images.githubusercontent.com/1932211/99357885-fbdd4380-28ac-11eb-972a-3deb8510a419.gif)

![QuarkusLevelDemo](https://user-images.githubusercontent.com/1932211/99358199-74440480-28ad-11eb-891b-3e2de1dd5783.gif)
