### ISSUE TITLE
'RESTEasy JAX-RS' should no longer be added by default

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#322]
https://code.quarkus.io/ no longer adds 'RESTEasy JAX-RS' by default, so the new project wizard should do the same

**Comment by fbricon** [comment]
It's not that trivial since https://code.quarkus.redhat.com/api is behind https://code.quarkus.io/api, and still includes it by default.

@ia3andy any way to detect whether we should flag 'RESTEasy JAX-RS' as included?

**Comment by ia3andy** [comment]
@fbricon yes, on https://code.quarkus.redhat.com/api/extensions it has the `default` flag to true, and to false on https://code.quarkus.io/api/extensions

**Comment by datho7561** [comment]
Sorry, just looking at this now. If I use the default options through the web UI at [code.quarkus.io](https://code.quarkus.io), or specify 0 extensions when querying the rest API, I still get this in the pom.xml:

```
...
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-resteasy</artifactId>
</dependency>
...
```

Is RESTEasy JAX-RS separate from quarkus-resteasy? Is RESTEasy JAX-RS is automatically added unless some other component is added? If so, which component do I need to add to prevent RESTEasy JAX-RS from being automatically added?

**Comment by ia3andy** [comment]
@datho7561 if you don't pick any other example, then the `quarkus-resteasy` example is added.

If you don't want any example, you need to add an extension with anouther example (ex: `quarkus-qute`) or to add `&ne=trye` which stand for `no examples`.

**Comment by datho7561** [comment]
@fbricon We could add another step to the wizard to specify if quickstart code should be generated, and add a warning that adding quickstart code may pull in other dependencies. Do you think this would be a good solution?

**Comment by ia3andy** [comment]
Hi @datho7561 ,

The api has changed since the discussion started, the parameter to use is `nc` ("No Code"), `ne` has been deprecated, the text to use in the wizard would be:
"Decide whether to include the starter code provided by extensions or get an empty Quarkus project."
If the answer is "Yes" then `nc=false`
If the answer is "No" then `nc=true`

It  would be nice to update this before it gets to delivered to the user.


The reason behind this is that we don't deliver sample code anymore but starter code, the nuance is subtile (starter code is meant to start your app while sample/example code is meant to learn and be deleted)

Let me know if you have any question :)

Cheers

**Comment by fbricon** [comment]
"Decide whether to include the starter code provided by extensions or get an empty Quarkus project." is not a yes-no question ;-)

**Comment by ia3andy** [comment]
@fbricon Sorry I wasn't precise enough :)
![image](https://user-images.githubusercontent.com/2223984/127297186-fbecde01-e34c-4313-9cba-ce69b0a7bdb8.png)

**Comment by ia3andy** [comment]
I am currently working on showing deprecated fields in https://code.quarkus.io/q/swagger-ui

**Comment by datho7561** [comment]
@ia3andy Going to fix this before the next release. How long are you planning on supporting the deprecated `ne` parameter?

**Comment by ia3andy** [comment]
@datho7561 it will not break even if kept, just it will include the code whatever its value when I remove the support. I don't have any specific date yet.
