### ISSUE TITLE
Generated quarkus project cannot be accessed after deployed to OpenShift

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-quarkus#325]
After pushing generated project to OpenShift cluster with odo v2.0.1 the url created by default cannot be opened in browser. Surprisingly when quarkus project created with odo using --starter project option everything is working as expected. The difference between two is the one generated with extension is using newer qurarkus artefacts and in log it say listening to http://localhost:8080. The one generated to odo is listening to http://0.0.0.0:8080.

After adding `-Dquarkus.http.host=0.0.0.0' to mvn command to run app in pod I was able to make it work, but that should be fixed in generated project to make it work OOTB.

**Comment by fbricon** [comment]
That's out of scope of the vscode extension. Should be done upstream in the quarkus project generator

**Comment by dgolovin** [comment]
Is there a way to just inject that host property value using 'create' command, like it is done here https://quarkus.io/guides/getting-started#bootstrapping-the-project?

**Comment by dgolovin** [comment]
Another option is to fix it in java-quarkus devfile. That is basically what I did to make it to work.

**Comment by dgolovin** [comment]
This issue has been fixed as part of https://github.com/openshift/odo/issues/4245.

**Comment by dgolovin** [comment]
^ @fbricon

**Comment by dgolovin** [comment]
still have the same issue with build from master.

**Comment by datho7561** [comment]
Hello Denis, I don't quite understand what you are trying to do. Here are a few quick questions:
- Where are you getting the URL which you are using to try to access the app? Is it the Code Lens above a REST-API method in the Java code, something from the `odo push` command, or something from the `mvn quarkus:dev` command?
- How are you running/debugging the Quarkus demo app? If you are trying to debug using the "Quarkus: Debug current Quarkus project" command, this will start and debug the project locally instead of on OpenShift
- How are you creating the odo component/devfile? (`odo create` --> `java-quarkus`?)
Thank you!

**Comment by dgolovin** [comment]
I was using branch with OpenShift connector integration.
Here are the steps:
1. Generate new project using java-quarkus ext
2. Push it to cluster using Quarkus provided command to push quarkus project to cluster
3. Wait until push command finishes 
3. Switch to OpenShift views container on sidebar
4. Find just deployed quarkus component in OpenShift: Appliacation Explorer
5. Use 'Open in Browser' from context menu on quarkus component

With successful push you still cannot reach the component webpage in browser. The reason is it starts server on 127.0.0.1 (you can see it through `Show log` command ) not 0.0.0.0.

**Comment by datho7561** [comment]
The link that's accessible in the OpenShift Connector sidebar in the application explorer works for me when I click on it. The "Open in browser" context menu option points to the same URL as well.

In my devfile, maven is passed a parameter that says to host on 0.0.0.0:
`mvn -Dmaven.repo.local=/home/user/.m2/repository quarkus:dev -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager`

From my understanding, `odo` is what generates the `devfile.yml` in the project directory. I know for sure its not vscode-quarkus nor the Quarkus project generator. If there is a configuration issue with the `devfile.yml`, maybe we can modify it in order to benefit other programs that use the script it specifies for launching the application.

Denis, can you confirm that your devfile for the generated project matches https://github.com/devfile/registry/blob/master/stacks/java-quarkus/devfile.yaml?

**Comment by dgolovin** [comment]
You are right! When I generate project using vscode-quarkus it works as expected.

**Comment by datho7561** [comment]
Hmm, okay. I guess there must have been a brief period where Quarkus used 0.0.0.0 but the devfile hadn't been configured to use it yet? Are you okay if I mark this as resolved upstream?

**Comment by dgolovin** [comment]
Sounds good to me.

**Comment by datho7561** [comment]
Resolved upstream in the Quarkus devfile
