### ISSUE TITLE
vscode-quarkus install is not working on vscode 1.46.1

### ISSUE THREAD

**Issue by abhiesa** [redhat-developer/vscode-quarkus#360]
I am working on Mac Catalina
My version of vscode is 1.46.1
While installing it says: Unable to install 'redhat.vscode-commons' extension because it is not compatible with current version of vscode (Version 1.46.1)

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (11 mos ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

**Comment by angelozerr** [comment]
@fbricon do you think it's possible to fix this issue?

**Comment by datho7561** [comment]
See #365, which is about removing the requirement of vscode-commons.

That being said, this extension depends on vscode-java. vscode-java will soon require a newer version of VS Code in order to support features like type hierarchy: https://github.com/redhat-developer/vscode-java/blob/master/package.json#L14. When installing vscode-quarkus, VS Code should install the newest vscode-java that works on your VS Code in order to meet vscode-quarkus's requirement. However, it would be best if you update your VS Code, since we don't fix bugs in older versions of our VS Code extensions.

**Comment by angelozerr** [comment]
I close this issue because we cannot support any version of vscode.
