### ISSUE TITLE
Add welcome page with Quarkus information

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-quarkus#53]
Can we add a welcome page with links to quarkus tutorials and information?

**Comment by angelozerr** [comment]
Github settings provide the capability to set a website (next to description), I think we should set the link https://quarkus.io/ 

I cannot do that since I'm not administrator of this github project. Here a sample of link:

![image](https://user-images.githubusercontent.com/1932211/63978799-95a5ae80-cab7-11e9-9bf0-0faa80873640.png)

**Comment by fbricon** [comment]
I believe @gorkem means a welcome page in the quarkus extension, similar to the one for the java extension pack

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/vscode-quarkus/pull/91
